# Generated by Django 3.1.5 on 2021-01-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pies', '0002_pie_categories'),
        ('jwt_auth', '0002_user_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='users', to='pies.Pie'),
        ),
    ]
