# Generated by Django 3.1.5 on 2021-01-27 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pies', '0002_pie_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='pies.pie')),
            ],
        ),
    ]
