# Generated by Django 3.1.5 on 2021-01-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pie',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
