# Generated by Django 3.1.5 on 2021-01-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('pies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pie',
            name='categories',
            field=models.ManyToManyField(related_name='pies', to='categories.Category'),
        ),
    ]
